name: Test coverage badge

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coverage-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[dev]'

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml
          coverage-badge -o documentation/badges/coverage.svg

      - name: Commit coverage badge
        run: |
          if git status --porcelain documentation/badges/coverage.svg | grep -q .; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add documentation/badges/coverage.svg
            git commit -m "chore: update coverage badge"
            git push
          else
            echo "No coverage badge changes to commit."
          fi
